### PR TITLE
Typedoc ci

### LINKED ISSUE #1052: docs ci test
check docs are up-to-date before merging to main

### PR DESCRIPTION
**Pull request by goastler**
fixes prosopo/captcha-private#659

### CODE REVIEW

**Review by forgetso — DISMISSED** [review]

**Review by forgetso — DISMISSED** [review]

**Comment by goastler** [comment]
this needs a change to the test layout. I'll do this in another pr

**Review by forgetso — DISMISSED** [review]

**Comment by forgetso** [comment]
> this needs a change to the test layout. I'll do this in another pr

please stick a ticket in for it :)

**Comment by goastler** [comment]
blocked by #1088

**Comment by goastler** [comment]
I've disabled the docs ci check until further notice because I can't get it working reliably on gha. The paths end up being different than on my local pc

We'll be fine without it atm as the publish workflow regens the docs before publishing

**Comment by HughParry** [comment]
Marking as draft, we can potentially close since we're moving away from typedoc iirc

**Comment by goastler** [comment]
closing this in favour of new branch system and change to the docs setup

**Pull request closed without merging**
