### PR TITLE
add cli bash script wrapper

### PR DESCRIPTION
**Pull request by goastler**
This allows us to do `./cli blah blah blah` instead of `npm run cli -- blah blah blah`

### CODE REVIEW

**Review by forgetso — DISMISSED** [review]
Should these files have .sh extensions so that people know what they are or is no file type a convention for some reason?

**Comment by goastler** [comment]
> Should these files have .sh extensions so that people know what they are or is no file type a convention for some reason?

I dropped the type just to make it shorter, otherwise you have to do `./cli.sh` instead of `./cli`, that's the only reason. Happy to add extensions back in?

**Comment by goastler** [comment]
alternatively I can add `#! /bin/bash` at the top to specify the shell type

**Comment by forgetso** [comment]
Happy to have no extensions if you put the header in the files.

**Review by HughParry — DISMISSED** [review]

**Comment by goastler** [comment]
> Happy to have no extensions if you put the header in the files.

done

**Comment by goastler** [comment]
closing as can use bash / zsh aliases, leave up to the user/dev

**Pull request closed without merging**
