### PR TITLE
Support Node >= v22

### PR DESCRIPTION
**Pull request by hckhanh**
To address https://github.com/prosopo/captcha/issues/1539

This change updates the import statements for JSON modules to use 'with' instead of 'assert'. This ensures compatibility with the latest module syntax standards and helps maintain consistency across the codebase.

### CODE REVIEW

**Comment by hckhanh** [comment]
I have tested with Node 20, It can run smoothly.

**Comment by forgetso** [comment]
HeY @hckhanh thanks very much for the PR! We'll get this in very soon.

**Comment by forgetso** [comment]
Hey @hckhanh we usually PR into the `staging` branch before we do a release. Would you mind resolving the package-lock.json conflicts? We'll merge it if it passes all the tests. Thanks again!

**Comment by hckhanh** [comment]
Sure I will do it

**Comment by forgetso** [comment]
@hckhanh thanks so much!

**Pull request merged**
